version: '3.8'
services:
  db:
    image: mysql:latest
    container_name: mysql_monitoreo
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: monitoreo
      MYSQL_USER: admin
      MYSQL_PASSWORD: adminpass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
